import React from 'react';

const AvisoLegal = () => {
    return (
        <div id="avisoLegal" >
            <div className="container">
                <h1 className="mb-5">AVISO LEGAL</h1>
                <h2 className="mb-4">1. TITULARIDAD DEL PORTAL.</h2>
                <p>Este sitio web (en adelante, el “Sitio Web”) es operado por Askartza Martxa (en adelante, la “Empresa”), una empresa legalmente constituida bajo las leyes de España, con domicilio en Sarriena Auzoa, 173, 48940 Leioa, Vizcaya.</p>
                <p>Puede ponerse en contacto con la Entidad a través del siguiente email: askartzamartxa@gmail.com</p>
                <p>El(los) nombre(s) de dominio(s) a través del cual(es) Vd. ha accedido al Portal es (son) titularidad de la Entidad. Dicho(s) nombre(s) de dominio(s) no podrá(n) ser utilizado(s) en conexión con otros contenidos, productos y/o servicios que no sean titularidad de la Entidad ni de manera que puedan causar confusión entre los usuarios finales o el descrédito de la Entidad.</p>
                
                <h2 className="mb-4 mt-5">2. OBJETO</h2>
                <p>El presente Aviso Legal recoge las condiciones generales que regulan el acceso, navegación y uso del Portal, así como de los contenidos que lo integran, y sin perjuicio de que la Entidad pueda establecer condiciones particulares que regulen la utilización, prestación y/o contratación de los productos o servicios que, en su caso, puedan ser ofrecidos a través del Portal.</p>
                <p>En caso de ser ofrecidos, a través del Portal, la utilización, prestación y/o contratación de productos o servicios, el hecho de ser utilizados y/o solicitados por el Usuario implicará, asimismo, la aceptación sin reservas de las condiciones particulares que, en su caso, hayan sido establecidas al efecto, y que formarán parte integrante del presente Aviso Legal.</p>
                <p>La Entidad se reserva la facultad de ofrecer determinados productos o servicios exclusivamente a los Usuarios registrados a través del Portal y que acepten expresamente las condiciones particulares que sean de aplicación.</p>
                <p>La Entidad se reserva la facultad de dar por terminado, modificar, suspender o interrumpir, temporalmente o de forma indefinida, en cualquier momento y sin necesidad de preaviso, el acceso a los productos, servicios y/o contenidos del Portal, así como la configuración misma del Portal, prestaciones, productos, servicios y contenidos, sin posibilidad por parte del Usuario de reclamar ni exigir indemnización alguna; en particular, con motivo de operaciones de mantenimiento, reparación, actualización, mejora y/o adecuación a cambios técnicos, operativos y/o legales. Tras dicha terminación, seguirán vigentes las prohibiciones, restricciones y limitaciones contenidas en el presente Aviso Legal y/o en cualesquiera condiciones particulares que sean de aplicación.</p>
                
                <h2 className="mb-4 mt-5">3. ACCESO Y USO DEL PORTAL</h2>
                <p>El mero acceso al Portal, el uso de los contenidos ofrecidos en el mismo, así como la cumplimentación de formularios, el envío de solicitudes de información, consultas, quejas y, en general, cualquier acto de naturaleza similar a los anteriores (es especial, si son realizados a través de los medios existentes en el Portal) implicará, por parte de quienes naveguen en el Portal, la adquisición de la consideración de Usuario y la aceptación, sin reservas, de todas y cada una de las normas integrantes del presente Aviso Legal. En consecuencia, todo Usuario debe leer atentamente y conocer el contenido del presente Aviso Legal.</p>
                <p>Salvo que se establezca expresamente lo contrario, el acceso y uso del Portal, por parte de los Usuarios, tiene carácter libre y gratuito. Ello no obstante, la Entidad se reserva la facultad, en exclusiva, de decidir si el acceso y uso de los productos o servicios, ofrecidos a través del Portal, tendrá carácter gratuito o si, por el contrario, decide exigir contraprestación económica por ello, en cuyo caso la cuantía, forma de pago y restantes condiciones particulares que resulten de aplicación serán expresamente notificadas a los Usuarios con antelación a su entrada en vigor, de manera que el Usuario pueda desistir voluntariamente del acceso y/o uso de aquellos productos o servicios que impliquen el abono de cantidad alguna. Una vez entren en vigor las condiciones particulares correspondientes, el acceso y/o uso de los productos o servicios por parte del Usuario implicará, por parte de éste, la aceptación expresa de las condiciones particulares.</p>
                <p>La utilización, prestación y/o contratación de los productos o servicios que, en su caso, puedan ser ofrecidos por la Entidad puede estar sujeta a la previa observancia de requisitos formales tales como el registro previo, la cumplimentación de formularios, formalizar la suscripción a los mismos, el abono de gastos o tasas y/o la previa aceptación de las condiciones particulares que resulten de aplicación a los mismos.</p>
                <p>Si para la utilización, prestación y/o contratación de algún producto o servicio ofrecido a través del Portal, el Usuario debiera proceder a su registro, éste será responsable de aportar información veraz y lícita, garantizando la autenticidad de todos aquellos datos que introduzca a la hora de cumplimentar los formularios preestablecidos para acceder a los productos o servicios de que se trate. Si como consecuencia del registro, el Usuario tuviera que hacer uso de una contraseña, éste se compromete a su uso diligente y a mantener la confidencialidad de la misma. En consecuencia, los Usuarios son responsables de la adecuada custodia y confidencialidad de cualesquiera identificadores y/o contraseñas que le sean suministrados por la Entidad, y se comprometen a no ceder su uso a terceros, ya sea temporal o permanente, ni a permitir su utilización por personas ajenas. Será responsabilidad exclusiva del Usuario la utilización y/o contratación de los productos o servicios ofrecidos en el Portal, por parte de cualquier tercero que, de forma ilegítima, emplee a tal efecto una contraseña o identificador suministrado al Usuario, cuando ello tenga lugar a causa de una actuación no diligente o la pérdida de la misma por el Usuario, a menos que el Usuario lo haya comunicado inmediatamente a la Entidad.</p>
                <p>En virtud de lo anterior, es obligación del Usuario notificar de forma inmediata a la Entidad, cualquier hecho que haga posible el uso indebido de los identificadores y/o contraseñas, tales como el robo, extravío, o el acceso no autorizado a los mismos por parte de terceros, con el fin de proceder a su inmediata cancelación. Mientras no se comuniquen tales hechos, la Entidad quedará eximida de cualquier responsabilidad que pudiera derivarse del uso indebido de los identificadores o contraseñas por parte de terceros no autorizados.</p>
                <p>En todo caso, el acceso, navegación y uso del Portal y, en su caso, el uso o contratación de los productos o servicios que sean ofrecidos a través del mismo se hace bajo la única y exclusiva responsabilidad del Usuario, por lo que éste se compromete a observar diligente y fielmente cualquier instrucción adicional, impartida por la Entidad o por personal autorizado de la Entidad, relativa al uso del Portal y sus contenidos.</p>
                <p>Por lo tanto, el Usuario se obliga a usar los contenidos, productos y servicios de forma diligente, correcta y lícita, de conformidad con la legislación vigente y, en particular, se compromete a abstenerse de:</p>
                <ol className="px-5">
                    <li>Utilizarlos con fines o efectos contrarios a la ley, a la moral, a las buenas costumbres generalmente aceptadas o al orden público y a las instrucciones recibidas de la Entidad.</li>
                    <li>Utilizarlos con fines lesivos de los legítimos derechos de terceros.</li>
                    <li>Emplear los contenidos y productos obtenidos a través del Portal o de los servicios, para remitir publicidad, comunicaciones con fines de venta directa o con cualquier otra clase de finalidad comercial, mensajes no solicitados dirigidos a una pluralidad de personas con independencia de su finalidad, así como abstenerse de comercializar o divulgar de cualquier modo dicha información, excepto cuando la Entidad lo autorice previa y expresamente.</li>
                </ol>    
                
                <h2 className="mb-4 mt-5">4. RESPONSABILIDADES, GARANTÍAS Y RENUNCIAS DE RESPONSABILIDAD.</h2>      
                <p>La Entidad no se hace responsable y, en la máxima medida permitida por la legislación aplicable, excluye cualesquiera garantías, expresas o implícitas, relativas a la mercantilidad, idoneidad para un fin concreto, no cumplimiento, exactitud, fiabilidad, integridad o actualidad de los contenidos, servicios, productos u otros elementos incluidos en el Portal, o los resultados obtenidos de acceder y usar el Portal y/o el contenido del mismo. El Portal y cualquier contenido, producto y/o servicio ofrecido dentro del mismo son ofrecidos “tal cual”. El Usuario es consciente y acepta voluntariamente que el uso de la información publicada y/o suministrada con relación a los productos o servicios del Portal tiene lugar bajo su única y exclusiva responsabilidad.</p>
                <p>En particular, en la máxima medida permitida por la legislación aplicable, la Entidad no garantiza ni se hace responsable de:</p>
                <ol className="px-5">
                    <li>La continuidad de los contenidos del Portal y/o la falta de disponibilidad o accesibilidad del Portal o continuidad técnica del mismo;</li>
                    <li>La existencia de interrupciones o errores en el acceso al Portal, así como problemas técnicos o fallos que se produzcan durante la conexión a Internet;</li>
                    <li>La ausencia de errores o inexactitudes en los contenidos, servicios o productos;</li>
                    <li>La ausencia de virus y demás componentes dañinos en el Portal o en el servidor que lo suministra;</li>
                    <li>La invulnerabilidad del Portal y/o la inexpugnabilidad de las medidas de seguridad que se adopten en el mismo;</li>
                    <li>La fiabilidad y/o adecuación, para un propósito o fin particular, del Portal, de los productos o servicios incorporados en el mismo, y de la información publicada y/o suministrada con relación a dichos productos o servicios;</li>
                    <li>En su caso, la falta de utilidad, beneficio o rendimiento de los contenidos o servicios del Portal;</li>
                    <li>Los daños o perjuicios que cause, a sí mismo o a un tercero, cualquier persona que infringiera las condiciones, normas e instrucciones que la Entidad establece en el Portal o a través de la vulneración de los sistemas de seguridad del mismo;</li>
                    <li>Cualesquiera otros daños que pudieran ser causados por motivos inherentes al no funcionamiento o al funcionamiento defectuoso del Portal o de los sitios web a los que, en su caso, se hayan podido establecer enlaces (links).</li>
                </ol>   
                
                <h2 className="mb-4 mt-5">5. PROHIBICIONES Y RESTRICCIONES.</h2>      
                <p>Queda prohibida cualquier comunicación o transmisión de contenidos que infrinja los derechos de terceros y/o cuyo contenido sea amenazante, obsceno, difamatorio, pornográfico, xenófobo, atentatorio contra la dignidad de la persona o los derechos de la infancia, la legalidad vigente o cualquier conducta que incite o constituya la realización de una infracción penal.</p>
                <p>Asimismo queda prohibida la inclusión y comunicación de contenidos, por parte de los Usuarios, que sean falsos o inexactos y que induzcan o puedan inducir a error al resto de Usuarios o al personal de la Entidad, en particular los contenidos que se encuentren protegidos por cualesquiera derechos de propiedad intelectual, industrial, de imagen o de naturaleza similar, pertenecientes a terceras personas, cuando ello dé lugar a una vulneración de la legislación vigente, no cuenten con la autorización del titular de los derechos, menoscaben o desprestigien la fama o crédito de la Entidad, sean considerados como un supuesto de publicidad ilícita, engañosa o desleal y/o incorporen virus o cualquier otro elemento electrónico que pudiese dañar o impedir el funcionamiento del Portal, de la red, equipos informáticos de la Entidad o terceros y/o el acceso al Portal por parte del resto de usuarios.</p>
                <p>Si el Usuario infringe las prohibiciones/restricciones anteriores, o la Entidad tiene o llegar a tener motivos razonables para sospechar que un Usuario ha incumplido cualquiera de las mismas, la Entidad se reserva el derecho de suspender o cancelar la cuenta del Usuario y negarle cualquier acceso y uso, actual o futuro, de los productos, servicios y/o del Portal (o cualquier parte del mismo).</p>
                
                <h2 className="mb-4 mt-5">6. DERECHOS DE PROPIEDAD INTELECTUAL E INDUSTRIAL.</h2>     
                <p>Quedan reservados todos los derechos de propiedad intelectual e industrial sobre los contenidos del Portal y, en particular, queda prohibido modificar, copiar, reproducir, comunicar públicamente, transformar o distribuir de cualquier forma la totalidad o parte de los contenidos incluidos en el Portal, para propósitos públicos o comerciales, si no se cuenta con la autorización previa, expresa y por escrito de la Entidad o, en su caso, del titular de los derechos al que correspondan.</p>
                <p>El acceso y navegación del Usuario por el Portal, así como el acceso y uso de los servicios o productos ofrecidos, en ningún caso se entenderá como una renuncia, transmisión, licencia o cesión total ni parcial de los derechos antes indicados por parte de la Entidad, excepto cuando se establezca expresamente lo contrario en las condiciones particulares que regulen la utilización, prestación y/o contratación de los productos o servicios que, en su caso, sean ofrecidos a través del Portal. En consecuencia, no está permitido suprimir, eludir o manipular el aviso de derechos de autor («copyright») y cualesquiera otros datos de identificación de los derechos de la Entidad o de sus titulares, incorporados a los contenidos, así como los dispositivos técnicos de protección, las huellas digitales o cualesquiera mecanismos de información y/o de identificación que pudieren contenerse en los mismos.</p>
                <p>Las referencias a nombres y marcas comerciales o registradas, logotipos u otros signos distintivos, ya sean titularidad de la Entidad o de terceras empresas, llevan implícitas la prohibición sobre su uso sin el consentimiento, previo, expreso y por escrito de la Entidad o de sus legítimos titulares. En ningún caso, salvo manifestación expresa en contrario, el acceso o uso del Portal y/o de sus contenidos, confiere al Usuario derecho alguno sobre las marcas, logotipos y/o signos distintivos en él incorporados.</p>
                <p>El uso, explotación y/o utilización no autorizada de los contenidos del Portal, así como cualquier acto de similar naturaleza del que se derive una lesión de los derechos de propiedad intelectual o industrial, dará lugar a las responsabilidades legalmente establecidas.</p>
                
                <h2 className="mb-4 mt-5">7. DURACIÓN Y MODIFICACIÓN.</h2>    
                <p>La Entidad se reserva el derecho de modificar el presente Aviso Legal y/o las condiciones particulares que, en su caso, hayan sido establecidas para la utilización y/o contratación de los productos o servicios prestados a través del Portal, cuando sea necesario a los efectos de adecuarse a los cambios legislativos, de negocio y/o tecnológicos. Los textos actualizados serán válidos y surtirán efecto desde su publicación en el Portal o, en su caso, una vez notificados a los Usuarios en los términos previstos en la referida notificación.</p>
                <p>La vigencia temporal de este Aviso Legal coincide, por lo tanto, con el tiempo de su exposición, hasta que sea modificado total o parcialmente, momento en el cual pasarán a tener vigencia los textos actualizados.</p>
                
                <h2 className="mb-4 mt-5">8. COMUNICACIONES.</h2>    
                <p>Para cualquier comunicación entre la Entidad y el Usuario, este deberá dirigirse a la Entidad a través de los medios de contacto arriba indicados, preferentemente por vía electrónica. En todo caso, y salvo que la ley determine expresamente otra cosa, las comunicaciones de la Entidad hacia el Usuario se realizarán preferentemente por vía electrónica, utilizando para ello los datos de contacto suministrados. El Usuario acepta expresamente la utilización del correo electrónico como procedimiento válido para el intercambio de información y la remisión de comunicaciones entre y/o con la Entidad.</p>
                
                <h2 className="mb-4 mt-5">9. GENERALIDADES.</h2>    
                <p>Los encabezamientos de las distintas cláusulas son sólo informativos, y no afectarán, calificarán o modificarán la interpretación del Aviso Legal.</p>
                <p>En caso de existir discrepancia entre lo establecido en este Aviso Legal y las condiciones particulares que, en su caso, puedan ser establecidas respecto de los productos o servicios ofrecidos en el Portal, prevalecerá lo dispuesto en las condiciones particulares respecto de los productos o servicios sujetos a dichas condiciones particulares.</p>
                <p>En el caso de que cualquier disposición o disposiciones de este Aviso Legal fuera(n) considerada(s) nula(s) o inaplicable(s), en su totalidad o en parte, por cualquier Juzgado, Tribunal u órgano administrativo competente, dicha nulidad o inaplicación no afectará a las otras disposiciones del Aviso Legal ni a las condiciones particulares que, en su caso, hayan podido ser establecidas.</p>
                <p>El no ejercicio o la no ejecución, por parte de la Entidad, de cualquier derecho o acción reconocida en este Aviso Legal no constituirá una renuncia al mismo, salvo reconocimiento y acuerdo por escrito por su parte.</p>
                
                <h2 className="mb-4 mt-5">10. LEGISLACIÓN APLICABLE Y TRIBUNALES COMPETENTES.</h2>   
                <p>El presente Aviso Legal y cualquier relación que surja de su aceptación o se relacione con el mismo se regirán exclusivamente por la legislación española que resulte de aplicación.</p>
                <p className="sin-margen">Cualquier controversia que surja o guarde relación con el uso de la página web o con el presente Aviso Legal será sometida a la jurisdicción no exclusiva de los juzgados y tribunales españoles. En el supuesto de que usted sea consumidor, usted podrá presentar la demanda en la ciudad donde tenga su domicilio de acuerdo con la legislación aplicable.</p>
            </div>
        </div>
    );
};

export default AvisoLegal;
